export const WALLET_TOAST_TEXT = {
  launchLoading: "Creating Your Game...",
  launchLoadingContent:'Your game is being deployed. Check your Profile > Game created section in a few minutes to view your creation.',
  launchSuccess: "Launch Successful!",
  launchSuccessContent: "Your game token is now live! View it in your profile or start sharing with others.",
  launchFailed: "Launch Failed",
  launchFailedContent: "Unable to launch token due to [specific reason]. Please try again or contact support if the issue persists.",

  purchaseLoading: "Transaction in Progress",
  purchaseLoadingContent: "Your purchase is being processed. This usually takes 15-30 seconds.",
  purchaseSuccess: "Purchase Complete!",
  purchaseSuccessContent: "You've successfully purchased tokens. Thank you for supporting this game!",
  purchaseFailed: "Purchase Failed",
  purchaseFailedContent: "Transaction couldn't be completed. Please try again or contact support.",

  saleLoading: "Processing Your Sale",
  saleLoadingContent: "Your tokens are being sold. Funds will be available in your wallet shortly.",
  saleSuccess: "Sale Complete!",
  saleSuccessContent: "Successfully sold. Funds have been credited to your wallet.",
  saleFailed: "Sale Failed",
  saleFailedContent: "Unable to complete sale. Please try again or contact support.",

  approvalLoading: "Approving Access",
  approvalLoadingContent: "Authorizing smart contract to trade tokens on your behalf. This only needs to be done once.",  
  approvalSuccess: "Access Approved",
  approvalSuccessContent: "Token permissions granted successfully. You can now proceed with trading.",
  approvalFailed: "Approval Failed",
  approvalFailedContent: "Something went wrong with the approval process. Please try again or contact support.",

  awakenLoading: "Awakening X-agent",
  awakenLoadingContent: "Awakening your X-agent. This usually takes 15-30 seconds.",
  awakenSuccess: "Awakening Complete!",
  awakenSuccessContent: "Successfully awakened your X-agent. You can now proceed with trading.",
  awakenFailed: "Awakening Failed",
  awakenFailedContent: "Unable to complete awakening. Please try again or contact support.",
};
